/* 
 * pollination-server
 *
 * Pollination Server OpenAPI Definition
 *
 * Contact: info@pollination.cloud
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace PollinationSDK
{
    /// <summary>
    /// BodyPostPluginOwnerPluginsPost
    /// </summary>
    [DataContract(Name = "Body_post_plugin__owner__plugins_post")]
    public partial class BodyPostPluginOwnerPluginsPost : IEquatable<BodyPostPluginOwnerPluginsPost>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BodyPostPluginOwnerPluginsPost" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BodyPostPluginOwnerPluginsPost() 
        { 
            // Set non-required readonly properties with defaultValue
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="BodyPostPluginOwnerPluginsPost" /> class.
        /// </summary>
        /// <param name="package">package (required).</param>
        public BodyPostPluginOwnerPluginsPost
        (
           System.IO.Stream package// Required parameters
           // Optional parameters
        )// BaseClass
        {
            // to ensure "package" is required (not null)
            this.Package = package ?? throw new ArgumentNullException("package is a required property for BodyPostPluginOwnerPluginsPost and cannot be null");

            // Set non-required readonly properties with defaultValue
        }


        /// <summary>
        /// Gets or Sets Package
        /// </summary>
        [DataMember(Name = "package", IsRequired = true, EmitDefaultValue = false)]
        public System.IO.Stream Package { get; set; } 

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "BodyPostPluginOwnerPluginsPost";
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString(bool detailed)
        {
            if (!detailed)
                return this.ToString();
            
            var sb = new StringBuilder();
            sb.Append("BodyPostPluginOwnerPluginsPost:\n");
            sb.Append("  Package: ").Append(Package).Append("\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the object from JSON string
        /// </summary>
        /// <returns>BodyPostPluginOwnerPluginsPost object</returns>
        public static BodyPostPluginOwnerPluginsPost FromJson(string json)
        {
            var obj = JsonConvert.DeserializeObject<BodyPostPluginOwnerPluginsPost>(json, JsonSetting.AnyOfConvertSetting);
            if (obj == null)
                return null;
            return obj.Type.ToLower() == obj.GetType().Name.ToLower() ? obj : null;
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>BodyPostPluginOwnerPluginsPost object</returns>
        public virtual BodyPostPluginOwnerPluginsPost DuplicateBodyPostPluginOwnerPluginsPost()
        {
            return FromJson(this.ToJson());
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>OpenAPIGenBaseModel</returns>
        public override OpenAPIGenBaseModel Duplicate()
        {
            return DuplicateBodyPostPluginOwnerPluginsPost();
        }

     
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            input = input is AnyOf anyOf ? anyOf.Obj : input;
            return this.Equals(input as BodyPostPluginOwnerPluginsPost);
        }

        /// <summary>
        /// Returns true if BodyPostPluginOwnerPluginsPost instances are equal
        /// </summary>
        /// <param name="input">Instance of BodyPostPluginOwnerPluginsPost to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BodyPostPluginOwnerPluginsPost input)
        {
            if (input == null)
                return false;
            return 
                (
                    this.Package == input.Package ||
                    (this.Package != null &&
                    this.Package.Equals(input.Package))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Package != null)
                    hashCode = hashCode * 59 + this.Package.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
