/* 
 * pollination-server
 *
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 0.18.0-beta.4
 * Contact: info@pollination.cloud
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PollinationSDK.Client.OpenAPIDateConverter;

namespace PollinationSDK.Model
{
    /// <summary>
    /// SubscriptionCreate
    /// </summary>
    [DataContract]
    public partial class SubscriptionCreate :  IEquatable<SubscriptionCreate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionCreate" /> class.
        /// </summary>
        /// <param name="items">The list of recurring price items and the quantity of each to attach to the new subscription.</param>
        public SubscriptionCreate
        (
           // Required parameters
           List<NewSubscriptionItem> items= default// Optional parameters
        )// BaseClass
        {
            this.Items = items;

            // Set non-required readonly properties with defaultValue
        }
        
        /// <summary>
        /// The list of recurring price items and the quantity of each to attach to the new subscription
        /// </summary>
        /// <value>The list of recurring price items and the quantity of each to attach to the new subscription</value>
        [DataMember(Name="items", EmitDefaultValue=false)]
        [JsonProperty("items")]
        public List<NewSubscriptionItem> Items { get; set; } 
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubscriptionCreate {\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented, JsonSetting.ConvertSetting);
        }

        /// <summary>
        /// Returns the object from JSON string
        /// </summary>
        /// <returns>SubscriptionCreate object</returns>
        public static SubscriptionCreate FromJson(string json)
        {
            var obj = JsonConvert.DeserializeObject<SubscriptionCreate>(json, JsonSetting.ConvertSetting);
            return obj;
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>SubscriptionCreate object</returns>
        public SubscriptionCreate DuplicateSubscriptionCreate()
        {
            return FromJson(this.ToJson());
        }
     
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SubscriptionCreate);
        }

        /// <summary>
        /// Returns true if SubscriptionCreate instances are equal
        /// </summary>
        /// <param name="input">Instance of SubscriptionCreate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubscriptionCreate input)
        {
            if (input == null)
                return false;
            return 
                (
                    this.Items == input.Items ||
                    this.Items != null &&
                    input.Items != null &&
                    this.Items.SequenceEqual(input.Items)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Items != null)
                    hashCode = hashCode * 59 + this.Items.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
