/* 
 * pollination-server
 *
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 0.25.0
 * Contact: info@pollination.cloud
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PollinationSDK.Client.OpenAPIDateConverter;

namespace PollinationSDK.Model
{
    /// <summary>
    /// TaxAmount
    /// </summary>
    [DataContract]
    public partial class TaxAmount :  IEquatable<TaxAmount>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaxAmount" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TaxAmount() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TaxAmount" /> class.
        /// </summary>
        /// <param name="amount">amount (required).</param>
        /// <param name="inclusive">inclusive (required).</param>
        /// <param name="taxRate">taxRate (required).</param>
        public TaxAmount
        (
           int amount, bool inclusive, string taxRate// Required parameters
           // Optional parameters
        )// BaseClass
        {
            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new InvalidDataException("amount is a required property for TaxAmount and cannot be null");
            }
            else
            {
                this.Amount = amount;
            }
            
            // to ensure "inclusive" is required (not null)
            if (inclusive == null)
            {
                throw new InvalidDataException("inclusive is a required property for TaxAmount and cannot be null");
            }
            else
            {
                this.Inclusive = inclusive;
            }
            
            // to ensure "taxRate" is required (not null)
            if (taxRate == null)
            {
                throw new InvalidDataException("taxRate is a required property for TaxAmount and cannot be null");
            }
            else
            {
                this.TaxRate = taxRate;
            }
            

            // Set non-required readonly properties with defaultValue
        }
        
        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        [JsonProperty("amount")]
        public int Amount { get; set; } 
        /// <summary>
        /// Gets or Sets Inclusive
        /// </summary>
        [DataMember(Name="inclusive", EmitDefaultValue=false)]
        [JsonProperty("inclusive")]
        public bool Inclusive { get; set; } 
        /// <summary>
        /// Gets or Sets TaxRate
        /// </summary>
        [DataMember(Name="tax_rate", EmitDefaultValue=false)]
        [JsonProperty("tax_rate")]
        public string TaxRate { get; set; } 
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TaxAmount {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Inclusive: ").Append(Inclusive).Append("\n");
            sb.Append("  TaxRate: ").Append(TaxRate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented, JsonSetting.ConvertSetting);
        }

        /// <summary>
        /// Returns the object from JSON string
        /// </summary>
        /// <returns>TaxAmount object</returns>
        public static TaxAmount FromJson(string json)
        {
            var obj = JsonConvert.DeserializeObject<TaxAmount>(json, JsonSetting.ConvertSetting);
            return obj;
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>TaxAmount object</returns>
        public TaxAmount DuplicateTaxAmount()
        {
            return FromJson(this.ToJson());
        }
     
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TaxAmount);
        }

        /// <summary>
        /// Returns true if TaxAmount instances are equal
        /// </summary>
        /// <param name="input">Instance of TaxAmount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaxAmount input)
        {
            if (input == null)
                return false;
            return 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.Inclusive == input.Inclusive ||
                    (this.Inclusive != null &&
                    this.Inclusive.Equals(input.Inclusive))
                ) && 
                (
                    this.TaxRate == input.TaxRate ||
                    (this.TaxRate != null &&
                    this.TaxRate.Equals(input.TaxRate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.Inclusive != null)
                    hashCode = hashCode * 59 + this.Inclusive.GetHashCode();
                if (this.TaxRate != null)
                    hashCode = hashCode * 59 + this.TaxRate.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
