//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace PollinationSDK.Interface.Domains.Applications
{
	public partial interface IEntities {}
}

//Classes implemented this interface:
namespace PollinationSDK
{
	public partial class DeploymentConfig: PollinationSDK.Interface.Domains.Applications.IEntities {}
}
