//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace PollinationSDK.Interface.Server.Rest.SubscriptionPlans
{
	public partial interface IDto {}
}

//Classes implemented this interface:
namespace PollinationSDK
{
	public partial class BillingOption: PollinationSDK.Interface.Server.Rest.SubscriptionPlans.IDto {}
	public partial class QuotaPlan: PollinationSDK.Interface.Server.Rest.SubscriptionPlans.IDto {}
	public partial class SubscriptionPlan: PollinationSDK.Interface.Server.Rest.SubscriptionPlans.IDto {}
}
