version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_name: "LBT.RestSharp"
          update_type: "all"
      - match:
          dependency_name: "QueenbeeSDK"
          update_type: "all"
    ignored_updates:
      - match:
          dependency_name: "System.ComponentModel.Annotations"
      - match:
          dependency_name: "Serilog.Sinks.File"
    commit_message:
      prefix: "fix"
      include_scope: true
