name: CD

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2

      - name: Update Assembly Version
        run: |
          python .openapi-generator/update_assembly_version.py

      - name: Build
        run: |
          dotnet restore
          dotnet build --configuration Release /nowarn:CS0472
          
      - name: Run Unit Tests
        run: |
          nuget install NUnit.ConsoleRunner -Version 3.10.0 -OutputDirectory packages
          ./packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe src/PollinationSDK.Test/bin/Release/netcoreapp3.1/PollinationSDK.Test.dll

      - name: Deploy
        working-directory: src/PollinationSDK
        run: |
          dotnet pack --configuration Release
          dotnet nuget push bin\Release\PollinationSDK.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
